config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'sign_out', to: 'sessions#destroy', as: 'sign_out'

  resources :sessions, only: %i[create destroy]

  get 'profiles/edit', to: 'user_profiles#edit'
  match 'profiles', to: 'user_profiles#update', via: %i[post patch]

  resources :user_profiles, path: :profiles, as: :profiles, only: %i[index show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  %w[400 404 500].each do |code|
    get code, to: 'errors#show', code: code
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/subject.rb
# frozen_string_literal: true

class Subject < ApplicationRecord
  has_many :user_profile_subjects, dependent: :destroy
  has_many :user_profile, through: :user_profile_subjects
end

app/models/user.rb
# frozen_string_literal: true

# User is a class that inherits from ApplicationRecord
class User < ApplicationRecord
  has_one :user_profile, dependent: :destroy
  class << self
    def find_or_create_from_auth_hash(auth_hash)
      user_params = user_params_from_auth_hash(auth_hash)
      User.find_or_create_by(provider: user_params[:provider], uid: user_params[:uid]) do |user|
        user.update(user_params)
      end
    end

    private

    def user_params_from_auth_hash(auth_hash)
      {
        name: auth_hash.info.name,
        provider: auth_hash.provider,
        uid: auth_hash.uid,
        email: auth_hash.info.email,
        image: auth_hash.info.image
      }
    end
  end

  def profile_registered?
    !user_profile.nil?
  end
end

app/models/user_profile.rb
# frozen_string_literal: true

# model for UserProfile
class UserProfile < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  has_many :user_profile_subjects, dependent: :destroy
  has_many :subjects, through: :user_profile_subjects

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze

  validates :name, presence: true, length: { maximum: 128 }
  validates :name_kana, length: { maximum: 128 }, allow_nil: true
  validates :nickname, length: { maximum: 128 }, allow_nil: true
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }
  validates :major_subject, presence: true, length: { maximum: 255 }
  validates :started, numericality: { only_integer: true, greater_than_or_equal_to: Date.current.year - 10,
                                      less_than_or_equal_to: Date.current.year + 10 }
  validates :pbl, length: { maximum: 128 }, allow_nil: true
  validates :favorite_food, length: { maximum: 128 }, allow_nil: true
  validates :hated_food, length: { maximum: 128 }, allow_nil: true

  def personal_profile?
    nickname.present? && work.present? && hobby.present? && favorite_food.present? && hated_food.present?
  end

  def school_profile?
    background.present? && pbl.present?
  end
end

app/models/user_profile_subject.rb
# frozen_string_literal: true

class UserProfileSubject < ApplicationRecord
  belongs_to :user_profile
  belongs_to :subject
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# ApplicationController is a class that inherits from ActionController::Base
class ApplicationController < ActionController::Base
  include SessionsHelper
  before_action :signed_in

  def signed_in
    return if current_user

    redirect_to root_path
  end
end

app/controllers/errors_controller.rb
# frozen_string_literal: true

# ErrorsController
class ErrorsController < ApplicationController
  layout 'full'

  def show
    @status_code = params[:code] || 500
    @message = message(@status_code)

    render 'default', status: @status_code
  end

  private

  def message(code)
    case code.to_i
    when 400
      '不正なリクエストです。'
    when 404
      'ページが見つかりません。'
    else
      'サーバエラーが発生しました。'
    end
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# HomeController is a class that inherits from ApplicationController
class HomeController < ApplicationController
  layout 'full'
  skip_before_action :signed_in, only: :index

  def index
    redirect_to profiles_path if current_user
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

# SessionsController is a class that inherits from ApplicationController
class SessionsController < ApplicationController
  skip_before_action :signed_in, only: :create

  def create
    email = auth_hash.info.email
    return redirect_to root_path, alert: '@aiit.ac.jp ドメインのみがログイン可能です。' unless email.match?(/.*@aiit.ac.jp/)

    if (user = User.find_or_create_from_auth_hash(auth_hash))
      sign_in user
      return redirect_to profiles_path
    end
    redirect_to root_path
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/test_controller.rb
class TestController < ApplicationController
  def new
  end
end

app/controllers/user_profiles_controller.rb
# frozen_string_literal: true

# Controller for create and edit UserProfile
class UserProfilesController < ApplicationController
  before_action :set_info, only: %i[edit update]
  before_action :signed_in, only: %i[index show edit update]

  def index
    @user_profiles = UserProfile.all.page(params[:page])
  end

  def show
    @profile = UserProfile.find(params[:id])
  end

  def edit
    if current_user.profile_registered?
      @user_profile = current_user.user_profile
    else
      @user_profile = current_user.build_user_profile
      @user_profile.name = current_user.name
      @user_profile.email = current_user.email
    end
    @user_profile.image = current_user.image
  end

  def update
    @user_profile = current_user_profile
    @user_profile.assign_attributes profile_params
    @user_profile.image = current_user.image

    if @user_profile.save
      redirect_to profile_path @user_profile
    else
      render 'edit'
    end
  end

  private

  def profile_params
    params.require(:user_profile).permit(
      :name, :name_kana, :nickname, :email,
      :major_subject, :started, :work, :background, :pbl,
      :hobby, :favorite_food, :hated_food, :other,
      subject_ids: []
    )
  end

  def set_info
    @major_subject = %w[事業設計工学 情報アーキテクチャ 創造技術]
    @subjects = Subject.all
  end

  def current_user_profile
    current_user.profile_registered? ? current_user.user_profile : current_user.build_user_profile
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

ICONS = {
  '事業設計工学' => '<span class="material-icons">build</span>',
  '情報アーキテクチャ' => '<span class="material-icons">computer</span>',
  '創造技術' => '<span class="material-icons">business</span>'
}.freeze

module ApplicationHelper
  # コースに対応するアイコンを返す
  def major_subject_icon(major_subject_name)
    ICONS[major_subject_name]
  end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

# SessionsHelper are implementations of home
module HomeHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

# SessionsHelper are implementations of auth
module SessionsHelper
  def current_user
    return unless (user_id = session[:user_id])

    @current_user ||= User.find_by(id: user_id)
  end

  def sign_in(user)
    session[:user_id] = user.id
  end

  def sign_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/test_helper.rb
# frozen_string_literal: true

module TestHelper
end

app/helpers/user_profiles_helper.rb
# frozen_string_literal: true

# Helper for UserProfile
module UserProfilesHelper
end

app/views/home/index.html.erb
<div class="top">
  <div class="top__container container">
    <h1 class="top__title">AIIT Student Profile</h1>
    <% if alert %>
      <div class="alert alert-danger" role="alert">
        <%= alert %>
      </div>
    <% end %>
    <p class="top__description">
      AIIT Student Profile は簡単にプロフィールを作成できるサービスです。<br>
      グループワークでの自己紹介タイムで簡単にわかりやすく自己紹介ができます。
    </p>
    <a class="btn btn-primary btn-lg top_button" href="/auth/google_oauth2" role="button" data-method="post">さっそくログインする</a>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  © 2021 Copyright: 2021年度コラボレイティブ開発特論Team1
</footer>

app/views/layouts/_head.html.erb
<head>
  <title><%= content_for?(:title) ? yield(:title) + ' - ' : '' %>AIIT Student Profile</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= favicon_link_tag('favicon.ico') %>
  <!-- Noto Sans Japanese Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100&display=swap" rel="stylesheet">
  <!-- Google Material Icons -->
  <link href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Round|Material+Icons+Sharp|Material+Icons+Two+Tone" rel="stylesheet">

  <%= render 'layouts/shim' %>
</head>

app/views/layouts/_header.html.erb
<header class="header navbar">
  <div class="container">
    <a class="header_title" href="<%= profiles_path %>">
      <h1 class="header_title__content">AIIT Student Profile</h1>
    </a>
    <nav class="navbar navbar-expand-lg">
      <ul class="header_menu navbar-nav">
        <% unless params[:controller] == 'user_profiles' && params[:action] == 'index' %>
          <li class="nav-item">
            <%= link_to profiles_path, class: 'nav-link' do %>
              <span class="material-icons">list</span>
              他のプロフを見る
            <% end %>
          </li>
        <% end %>
        <% unless params[:controller] == 'user_profiles' && %w(new edit create).include?(params[:action]) %>
         <li class="nav-item">
           <%= link_to profiles_edit_path, class: 'nav-link' do %>
             <span class="material-icons">edit</span>
             プロフを編集する
           <% end %>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <%= render 'layouts/head' %>

  <body>
    <%= render 'layouts/header' %>
    <div class="main_content container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/full.html.erb
<!DOCTYPE html>
<html lang="ja">
  <%= render 'layouts/head' %>

  <body>
    <div class="main_content--full">
      <%= yield %>
    </div>
  </body>
</html>

app/views/user_profiles/_form.html.erb
<%= form_with(model: @user_profile, url: profiles_path, local: true) do |f| %>
  <div class="user_profile">
    <div class="field_group">
      <div class="subtitle">
        <span class="material-icons">insert_drive_file</span>
        基本情報
      </div>
      <%= f.label :name, '名前', class: 'form-required' %>
      <%= f.text_field :name, placeholder: "小山 きよみ", class: 'form-control' %>
      <% if @user_profile.errors.include?(:name) %>
        <div class="error_message_container">
          <% @user_profile.errors.full_messages_for(:name).each do |msg| %>
            <p class="error_message"><%= msg %></p>
          <% end %>
        </div>
      <% end %>

      <%= f.label :name_kana, 'ふりがな' %>
      <%= f.text_field :name_kana, placeholder: "こやま きよみ", class: 'form-control' %>

      <%= f.label :email, 'メールアドレス', class: 'form-required' %>
      <%= f.text_field :email, placeholder: "a2100ab@aiit.ac.jp", class: 'form-control' %>
      <% if @user_profile.errors.include?(:email) %>
        <div class="error_message_container">
          <% @user_profile.errors.full_messages_for(:email).each do |msg| %>
            <p class="error_message"><%= msg %></p>
          <% end %>
        </div>
      <% end %>

      <%= f.label :major_subject, 'コース', class: 'form-required' %>
      <%= f.select(:major_subject, 
                  @major_subject.map{ |value| [value, value] },
                  { :prompt => '選択してください' },
                  { :class => 'form-select' })
                  %>
      <% if @user_profile.errors.include?(:major_subject) %>
        <div class="error_message_container">
          <% @user_profile.errors.full_messages_for(:major_subject).each do |msg| %>
            <p class="error_message"><%= msg %></p>
          <% end %>
        </div>
      <% end %>

      <%= f.label :started, '入学年', class: 'form-required' %>
      <%= f.text_field :started, placeholder: "2021", class: 'form-control' %>
      <% if @user_profile.errors.include?(:started) %>
        <div class="error_message_container">
          <% @user_profile.errors.full_messages_for(:started).each do |msg| %>
            <p class="error_message"><%= msg %></p>
          <% end %>
        </div>
      <% end %>

      <%= f.label :other, '自己紹介' %>
      <%= f.text_area :other, placeholder: "こんにちは！\n情報アーキテクトとプロジェクトマネジメントに興味があります。\nよろしくおねがいします。", rows: 5, class: 'form-control' %>

      <label>プロフィール画像</label>
      <%= image_tag @user_profile.image, class: 'user_profile_img' %>
    </div>

    <div class="field_group">
      <div class="subtitle">
        <span class="material-icons">person</span>
        個人プロフィール
      </div>
      <div>
        <%= f.label :nickname, 'ニックネーム' %>
        <%= f.text_field :nickname, placeholder: "tobby", class: 'form-control' %>

        <%= f.label :work, '仕事' %>
        <%= f.text_field :work, placeholder: 'コンサル会社でPMをやっています。', class: 'form-control' %>

        <%= f.label :hobby, '趣味' %>
        <%= f.text_area :hobby, placeholder: "サッカー観戦とウィスキー集め", class: 'form-control' %>

        <%= f.label :favorite_food, '好きな食べ物' %>
        <%= f.text_field :favorite_food, placeholder: "蟹", class: 'form-control' %>

        <%= f.label :hated_food, '嫌いな食べ物' %>
        <%= f.text_field :hated_food, placeholder: "なんでも食べます。", class: 'form-control' %>
      </div>
    </div>

    <div class="field_group">
      <div class="subtitle">
        <span class="material-icons">school</span>
        学校プロフィール
      </div>
      <div>
        <%= f.label :background, '入学した経緯' %>
        <%= f.text_area :background, placeholder: 'エンジニアになって圧倒的成長をして年収1000万円になるため。', class: 'form-control' %>

        <%= f.label :pbl, '入りたいPBL' %>
        <%= f.text_field :pbl, placeholder: "小山PBL 三好PBL", class: 'form-control' %>

        <%= f.label :user_profile_subjects, '受講した科目' %>
        <%= f.collection_check_boxes :subject_ids, @subjects, :id, :name do |b| %>
          <div>
            <%= b.label class:"checkbox" do %>
              <%= b.check_box %>
              <span><%= b.text %></span>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="col-6 mx-auto d-flex justify-content-center">
      <%= f.submit '保存する', class: 'btn btn-primary btn-lg' %>
    </div>
  </div>
<% end %>

app/views/user_profiles/edit.html.erb
<% content_for(:title, 'プロフィール編集') %>

<div class="row">
  <div class="col-md-6 offset-3">
    <%= render 'form', user_profile: @user_profile %>
  </div>
</div>

app/views/user_profiles/index.html.erb
<% content_for(:title, 'プロフィールリスト') %>

<ul class="users">
  <% @user_profiles.each do |user_profile| %>
    <li class="bg-palegreen user_profile">
      <a href="<%= profile_path(user_profile) %>">
        <% if user_profile.image.present? %>
          <img src="<%= user_profile.image %>" alt="" class="user_profile__photo">
        <% else %>
          <span class="material-icons user_profile__photo">account_box</span>
        <% end %>
        <div class="user_profile__info">
          <span class="username"><%= user_profile.name %></span>
          <span class="major_subject">
            <%== major_subject_icon(user_profile.major_subject) %>
            <span class="major_subject_name"><%= user_profile.major_subject %></span>
          </span>
          <% if user_profile.other.present? %>
            <span class="other"><%= user_profile.other.truncate(200) %></span>
          <% end %>
        </div>
      </a>
    </li>
  <% end %>
</ul>

<%= paginate @user_profiles %>

app/views/user_profiles/show.html.erb
<% content_for(:title, @profile.name + ' さんのプロフィール') %>

<div class="base_profile">
  <% if @profile.image.present? %>
    <img src="<%= @profile.image %>" alt="" class="base_profile__photo">
  <% else %>
    <span class="base_profile__photo material-icons">account_box</span>
  <% end %>
  <div class="base_profile__info">
    <% if @profile.name_kana.present? %>
      <span><%=  @profile.name_kana  %></span>
    <% end %>
    <h2 class="base_profile__name"><%= @profile.name %></h2>
    <ul class="base_profile_list">
      <li class="base_profile_list__item"><%== major_subject_icon(@profile.major_subject) %><%= @profile.major_subject %></li>
      <li class="base_profile_list__item"><span class="material-icons">school</span><%= @profile.started %>年入学</li>
      <li class="base_profile_list__item"><span class="material-icons">email</span><%= @profile.email %></li>
    </ul>
  </div>
</div>

<div class="profile_two_column_layout">
  <% if @profile.other.present? && @profile.school_profile? %>
    <div class="school_profile">
      <% if @profile.other.present? %>
        <h3 class="school_profile__heading"><span class="material-icons">short_text</span>自己紹介</h3>
        <div class="school_profile__content"><%= simple_format(@profile.other) %></div>
      <% end %>

      <% if @profile.school_profile? %>
        <div class="school_profile__content">
          <div class="definition_list">
            <% if @profile.background.present? %>
              <span class="definition_list__term">入学した経緯</span>
              <span><%= @profile.background %></span>
            <% end %>
            <% if @profile.pbl.present? %>
              <span class="definition_list__term">入りたいPBL</span>
              <span><%= @profile.pbl %></span>
            <% end %>
          </div>
        </div>
      <% end %>

      <% unless @profile.subjects.empty? %>
        <h3 class="school_profile__heading"><span class='material-icons'>check</span>受講した科目</h3>
        <ul>
          <% @profile.subjects.each do | subject | %>
            <li><%= subject.name %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
  <% elsif @profile.personal_profile? %>
    <p class="school_profile school_profile--empty">
      学校プロフィールがありません。
    </p>
  <% end %>

  <% if @profile.personal_profile? %>
    <div class="personal_profile">
      <div class="definition_list">
        <% if @profile.nickname.present? %>
          <span class="definition_list__term">ニックネーム</span>
          <span><%= @profile.nickname %></span>
        <% end %>
        <% if @profile.work.present? %>
          <span class="definition_list__term">仕事</span>
          <span><%= @profile.work %></span>
        <% end %>
        <% if @profile.hobby.present? %>
          <span class="definition_list__term">趣味</span>
          <span><%= @profile.hobby %></span>
        <% end %>
        <% if @profile.favorite_food.present? %>
          <span class="definition_list__term">好きな食べ物</span>
          <span><%= @profile.favorite_food %></span>
        <% end %>
        <% if @profile.hated_food.present? %>
          <span class="definition_list__term">嫌いな食べ物</span>
          <span><%= @profile.hated_food %></span>
        <% end %>
      </div>
    </div>
  <% end %>
</div>